// Code generated by protoc-gen-go.
// source: msg.proto
// DO NOT EDIT!

/*
Package protobuf is a generated protocol buffer package.

It is generated from these files:
	msg.proto

It has these top-level messages:
	A2BRequired
	A2BOptional
*/
package protobuf

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type A2BRequired struct {
	Field1           *uint64 `protobuf:"varint,1,req,name=field1" json:"field1,omitempty"`
	Field2           *uint64 `protobuf:"varint,2,opt,name=field2" json:"field2,omitempty"`
	Field3           *uint64 `protobuf:"varint,3,req,name=field3" json:"field3,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *A2BRequired) Reset()         { *m = A2BRequired{} }
func (m *A2BRequired) String() string { return proto.CompactTextString(m) }
func (*A2BRequired) ProtoMessage()    {}

func (m *A2BRequired) GetField1() uint64 {
	if m != nil && m.Field1 != nil {
		return *m.Field1
	}
	return 0
}

func (m *A2BRequired) GetField2() uint64 {
	if m != nil && m.Field2 != nil {
		return *m.Field2
	}
	return 0
}

func (m *A2BRequired) GetField3() uint64 {
	if m != nil && m.Field3 != nil {
		return *m.Field3
	}
	return 0
}

type A2BOptional struct {
	Field1           *uint64 `protobuf:"varint,1,req,name=field1" json:"field1,omitempty"`
	Field2           *uint64 `protobuf:"varint,2,opt,name=field2" json:"field2,omitempty"`
	Field3           *uint64 `protobuf:"varint,3,opt,name=field3" json:"field3,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *A2BOptional) Reset()         { *m = A2BOptional{} }
func (m *A2BOptional) String() string { return proto.CompactTextString(m) }
func (*A2BOptional) ProtoMessage()    {}

func (m *A2BOptional) GetField1() uint64 {
	if m != nil && m.Field1 != nil {
		return *m.Field1
	}
	return 0
}

func (m *A2BOptional) GetField2() uint64 {
	if m != nil && m.Field2 != nil {
		return *m.Field2
	}
	return 0
}

func (m *A2BOptional) GetField3() uint64 {
	if m != nil && m.Field3 != nil {
		return *m.Field3
	}
	return 0
}

func init() {
}
