#! /usr/bin/env python

# Initialise / Setup
env = Environment()

# Command-line Configuration

# Setting Options

# Setting up Construction Environment
env.Append( CPPPATH=[ '#./include' ] )
env.Append( LIBPATH='#.' )


# All environment configurations are done. Export.
Export( 'env')

# Build Target : Shared Library
# Source
c_palindrome    = env.File( 'palindrome.c' )
c_prime         = env.File( 'prime.c' )
c_sequence      = env.File( 'sequence.c' )
shlib_src       = [ c_prime, c_palindrome, c_sequence ]

t_libnumerical  = env.SharedLibrary( 
                    target='libnumerical', 
                    source=[ shlib_src ],
                    LIBS=['m'] )

# Build Targets : Subdirs
subdir_utils    = SConscript([ 'utils/Sconstruct' ])

Return( 't_libnumerical' )
