#include <stdio.h>
#include <stdlib.h>
#include <mytypes.h>
#include <math.h>
#include <prime.h>
#include <sequence.h>

/* xmldoc
 * <problem>
 *      <description>
 *          What is the value of the first triangle number to have over five 
 *          hundred divisors?
 *          A triangle number is generated by adding first n natural numbers
 *      </description>
 *      <insight>
 *          The number of positive divisors of a number of the form,
 *              n = p1^v1 * p2^v2 * pk^vk, where p is a prime number, 
 *          is given by,
 *              d(n) = (v1+1) * (v2 +1) * (vk+1)
 *      </insight>
 * </problem>
 */

u32 primes[10000000];

int main( void ) 
{
    u32 sum;
    u32 divisors, i, j;
    u32 fac[1000];
    u32 factors_count = 0;

    loadprimes( 0xFFFFFFF );
    for( i = 1; i < 10000000; i++) {
        divisors = 1;
        factors_count = 0;
        sum = (u32)sumofseq( i ); // Pray that the sum will be within u32 size.
        factors( sum, fac, &factors_count );
        for( j = 0; j < factors_count; j++ ) {
            primes[fac[j]]++; 
        }
        for( j = 0; j < factors_count ; j++ ) {
            if( primes[fac[j]] ) {
                divisors *= (primes[fac[j]] + 1);
                primes[fac[j]] = 0;
            }
        }
        if( sum == 76576500 ) {
            printf("i %u sum %u divisors %u factors %u\n", i, sum, divisors, 
                    factors_count);
            break;
        }
        for( j = 0; j < factors_count; j++ ) {
            primes[fac[j]] = 0;
        }
        if( divisors > 500 ) {
            printf("i %u sum %u divisors %u factors %u\n", i, sum, divisors, 
                    factors_count);
            break;
        }
    }
}
