#include <stdio.h>
#include <stdlib.h>
#include <mytypes.h>

/* xmldoc
 * <problem>
 *     <description>
 *         Each new term in the Fibonacci sequence is generated by adding the
 *         previous two terms. By starting with 1 and 2, the first 10 terms will
 *         be:
 *             1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *         Find the sum of all the even-valued terms in the sequence which do not
 *         exceed four million.
 *     </description>
 * </problem>
 */

u64 fibsum( u32 first, u32 second, u32 upto );

u64 fibsum( u32 first, u32 second, u32 upto )
{
    u64 sum = 0;
    if( second < upto ) {
        sum = fibsum( second, first + second, upto );
    }
    if( ! (second & 1) ) {
        return sum + second;
    } else {
        return sum;
    }
}

int main( void ) 
{
    printf( "%llu \n", fibsum( 1, 2, 4000000 ));
}
